version: '3.8'

services:
  jester:
    image: jester:latest
    build:
      context: .
    container_name: jester
    ports:
      - "8088:8088"
    environment:
      - DATABASE_URL=jester-db:5432/jester
    depends_on:
      - jester-db
    restart: always

  jester-db:
    image: postgres:latest
    container_name: jester-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=jester
    restart: always